### ISSUE TITLE
--icon option broken when building on MacOS for MacOS

### ISSUE THREAD

**Issue by TheVento** [electron-userland/electron-packager#309]
On my setup `electron-packager 6.0.0 / electron-prebuilt 0.37.5`, when for (and on) `MacOS 10.11.4 (15E65)`, the `electron-packager` option `--icon` seems broken. If I use it, the specified `.icns` file is renamed to `atom.icns` and included in the `.app`, while the App's `Info.plist` refers to `electron.icns` (which is also included and contains the default Icon), causing the desired Icon to be ignored.

Can anyone confirm/reproduce?

My suggestions for a build for MacOS with the `--icon` option enabled:
- Don't rename the `.icns` file, add it to the App as specified with `--icon`
- Modify the generation of the `Info.plist` to refer to the Icon file specified by `--icon`

Any comments / further ideas on this?

**Comment by malept** [comment]
Thanks for filing an issue on this. It's been fixed in master (#300/#301), but we're waiting for another pull request (#298) to get merged, which is also affected by Electron >= 0.37.4.

Two workarounds exist, until 6.0.1 is released:

* Install electron-packager using the GitHub syntax (see `npm install --help`)
* Package your Electron app using a version of Electron earlier than 0.37.4, for example 0.37.3.

**Comment by TheVento** [comment]
thanks... you are a genious!

**Comment by liuhong1happy** [comment]
Me too! When I use command line ('electron-packager ./app E360Player --icon=./build/logo.ico --platform=win32 --arch=x64 --version=0.36.9') on Mac,it spawn wine ENOENT.

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "pack-win32"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @ pack-win32: `electron-packager ./app E360Player --icon=./build/logo.ico --platform=win32 --arch=ia32 --version=0.36.9`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ pack-win32 script 'electron-packager ./app E360Player --icon=./build/logo.ico --platform=win32 --arch=ia32 --version=0.36.9'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager ./app E360Player --icon=./build/logo.ico --platform=win32 --arch=ia32 --version=0.36.9
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/liuhong/workdir/electron-360player/npm-debug.log

**Comment by malept** [comment]
@liuhong1happy this is a different problem than this issue describes, please read the section in our documentation on [building Windows apps from non-Windows platforms](https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms).

**Comment by tkambler** [comment]
Installed `electron-prebuilt` using GitHub syntax + `electron-prebuilt@0.37.3`:

```
$ npm i electron-userland/electron-packager electron-prebuilt@0.37.3 --save
```

Still doesn't work.

**Comment by malept** [comment]
@tkambler It should work for both Electron >= 0.37.4 and Electron <= 0.37.3 (there are unit tests for both), as of the released electron-packager 6.0.1.

A small, reproducible testcase is requested (you can use a fork of [electron-quick-start](https://github.com/electron/electron-quick-start)) so that someone can debug the issue with a reliable way to make it fail.

**Comment by MarshallOfSound** [comment]
@malept I am trying to use the `icon` option on electron `0.37.5` and it does not appear to be working

**Comment by malept** [comment]
@MarshallOfSound What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are you passing to the `packager()` function?

**Comment by MarshallOfSound** [comment]
@malept I am using the programmatic API.

As part of my settings object I have

```js
{
    ...

    icon: './build/assets/img/main',
    ...
}
```

The file `./build/assets/img/main.icns` exists

**Comment by malept** [comment]
@MarshallOfSound What version of electron-packager are you using? I cannot reproduce this, host platform is Linux, running electron-packager from git master, building with Electron 0.37.4. (I don't have access to a Mac on which to test.) I have verified via `sha256sum` that my icns is the same as `$APPNAME.app/Contents/Resources/electron.icns`.

The testcase comment I made [earlier](#issuecomment-210178470) applies here as well.

**Comment by MarshallOfSound** [comment]
I am running `electron-packager` `6.0.2` and using `electron-prebuilt` `0.37.6`.

Host platform is OS X

The project is here: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

I have only updated the `electron-packager` dependency locally though.

**Comment by MarshallOfSound** [comment]
@malept I also just deleted the `node_modules` directory.  Downgraded to `0.37.4` and tried again, same issue, the icon does not update.

**Comment by malept** [comment]
> The project is here: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

Haha, I knew that username looked familiar.

Could you see if `sha1sum src/assets/icons/main.icns` and `sha1sum "dist/Google Play Music Desktop Player-darwin-x64/Google Play Music Desktop Player.app/Contents/Resources/electron.icns"` yield the same checksum?

**Comment by MarshallOfSound** [comment]
@malept Interestingly enough, the shasum of those two files are identical...  But the icon when opening and when looking in finder are completely different

**Comment by malept** [comment]
I want to say I've seen a report of this before (and it was some sort of icon caching problem), but I can't seem to find the GitHub issue at the moment.

**Comment by MarshallOfSound** [comment]
@malept OK, I am thoroughly confused now.  I went through and cleaned out this folder

```
/var/folders/qf/96gzcfwd7yz1tws3q0mnk3tm0000gp/T/electron-packager/darwin-x64/Google Play Music Desktop Player-darwin-x64
```

And now the icon is working....
